version: '3'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
    - 80:80
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - ./digital_cash:/digital_cash
    environment:
      - RAILS_ENV=${RAILS_ENV}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db