# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 541406c9b4be41308548b432afbac4e0160719d9650f020407821536fe6be44679dd8b5179b135f47beda825f6e28c6ff12617b7a8e91dcee7d6f8704aa0d12a

test:
  secret_key_base: eee9e507a22f3a90c2d783f3f4f0ed842c3f7365121147a84248339297431196f7fa05a57c9896d3e3119647f70ebccf35d9b3abc38db66e959de5e16c1e398b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1fbb1e2e423d26dff59c87e09850370ba67135c9b69c5a680696e3ff339f2a5fbd129b1f21278cd6745e78faff11e6887539977eda8e95f026a4e01681541144
